var fish_data = [
    {
        "Name": "Bitterling",
        "Image": "NH-Icon-bitterling",
        "Price": 900,
        "Location": "River",
        "Shadowsize": 1,
        "Time": "All day",
        "Jan": true,
        "Feb": true,
        "Mar": true,
        "Apr": false,
        "May": false,
        "Jun": false,
        "Jul": false,
        "Aug": false,
        "Sep": false,
        "Oct": false,
        "Nov": true,
        "Dec": true
    },
    {
        "Name": "Pale chub",
        "Image": "NH-Icon-palechub",
        "Price": 200,
        "Location": "River",
        "Shadowsize": 1,
        "Time": "9 AM - 4 PM",
        "Jan": true,
        "Feb": true,
        "Mar": true,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": true,
        "Nov": true,
        "Dec": true
    },
    {
        "Name": "Crucian carp",
        "Image": "NH-Icon-cruciancarp",
        "Price": 160,
        "Location": "River",
        "Shadowsize": 2,
        "Time": "All day",
        "Jan": true,
        "Feb": true,
        "Mar": true,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": true,
        "Nov": true,
        "Dec": true
    },
    {
        "Name": "Dace",
        "Image": "NH-Icon-dace",
        "Price": 240,
        "Location": "River",
        "Shadowsize": 3,
        "Time": "4 PM - 9 AM",
        "Jan": true,
        "Feb": true,
        "Mar": true,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": true,
        "Nov": true,
        "Dec": true
    },
    {
        "Name": "Carp",
        "Image": "NH-Icon-carp",
        "Price": 300,
        "Location": "Pond",
        "Shadowsize": 4,
        "Time": "All day",
        "Jan": true,
        "Feb": true,
        "Mar": true,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": true,
        "Nov": true,
        "Dec": true
    },
    {
        "Name": "Koi",
        "Image": "NH-Icon-koi",
        "Price": "4,000",
        "Location": "Pond",
        "Shadowsize": 4,
        "Time": "4 PM - 9 AM",
        "Jan": true,
        "Feb": true,
        "Mar": true,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": true,
        "Nov": true,
        "Dec": true
    },
    {
        "Name": "Goldfish",
        "Image": "NH-Icon-goldfish",
        "Price": "1,300",
        "Location": "Pond",
        "Shadowsize": 1,
        "Time": "All day",
        "Jan": true,
        "Feb": true,
        "Mar": true,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": true,
        "Nov": true,
        "Dec": true
    },
    {
        "Name": "Pop-eyed goldfish",
        "Image": "NH-Icon-popeyedgoldfish",
        "Price": "1,300",
        "Location": "Pond",
        "Shadowsize": 1,
        "Time": "9 AM - 4 PM",
        "Jan": true,
        "Feb": true,
        "Mar": true,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": true,
        "Nov": true,
        "Dec": true
    },
    {
        "Name": "Ranchu goldfish",
        "Image": "NH-Icon-ranchugoldfish",
        "Price": "4,500",
        "Location": "Pond",
        "Shadowsize": 2,
        "Time": "9 AM - 4 PM",
        "Jan": true,
        "Feb": true,
        "Mar": true,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": true,
        "Nov": true,
        "Dec": true
    },
    {
        "Name": "Killifish",
        "Image": "NH-Icon-killifish",
        "Price": 300,
        "Location": "Pond",
        "Shadowsize": 1,
        "Time": "All day",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": false,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Crawfish",
        "Image": "NH-Icon-crawfish",
        "Price": 200,
        "Location": "Pond",
        "Shadowsize": 2,
        "Time": "All day",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Soft-shelled turtle",
        "Image": "NH-Icon-softshelledturtle",
        "Price": "3,750",
        "Location": "River",
        "Shadowsize": 4,
        "Time": "4 PM - 9 AM",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": false,
        "Jul": false,
        "Aug": true,
        "Sep": true,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Snapping Turtle",
        "Image": "NH-Icon-snappingturtle",
        "Price": "5,000",
        "Location": "River",
        "Shadowsize": 4,
        "Time": "9 PM - 4 AM",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": true,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Tadpole",
        "Image": "NH-Icon-tadpole",
        "Price": 100,
        "Location": "Pond",
        "Shadowsize": 1,
        "Time": "All day",
        "Jan": false,
        "Feb": false,
        "Mar": true,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": false,
        "Sep": false,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Frog",
        "Image": "NH-Icon-frog",
        "Price": 120,
        "Location": "Pond",
        "Shadowsize": 2,
        "Time": "All day",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": false,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Freshwater goby",
        "Image": "NH-Icon-freshwatergoby",
        "Price": 400,
        "Location": "River",
        "Shadowsize": 2,
        "Time": "4 PM - 9 AM",
        "Jan": true,
        "Feb": true,
        "Mar": true,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": true,
        "Nov": true,
        "Dec": true
    },
    {
        "Name": "Loach",
        "Image": "NH-Icon-loach",
        "Price": 400,
        "Location": "River",
        "Shadowsize": 2,
        "Time": "All day",
        "Jan": false,
        "Feb": false,
        "Mar": true,
        "Apr": true,
        "May": true,
        "Jun": false,
        "Jul": false,
        "Aug": false,
        "Sep": false,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Catfish",
        "Image": "NH-Icon-catfish",
        "Price": 800,
        "Location": "Pond",
        "Shadowsize": 4,
        "Time": "4 PM - 9 AM",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": true,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Giant snakehead",
        "Image": "NH-Icon-giantsnakehead",
        "Price": "5,500",
        "Location": "Pond",
        "Shadowsize": 4,
        "Time": "9 AM - 4 PM",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": false,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Bluegill",
        "Image": "NH-Icon-bluegill",
        "Price": 180,
        "Location": "River",
        "Shadowsize": 2,
        "Time": "9 AM - 4 PM",
        "Jan": true,
        "Feb": true,
        "Mar": true,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": true,
        "Nov": true,
        "Dec": true
    },
    {
        "Name": "Yellow perch",
        "Image": "NH-Icon-yellowperch",
        "Price": 300,
        "Location": "River",
        "Shadowsize": 3,
        "Time": "All day",
        "Jan": true,
        "Feb": true,
        "Mar": true,
        "Apr": false,
        "May": false,
        "Jun": false,
        "Jul": false,
        "Aug": false,
        "Sep": false,
        "Oct": true,
        "Nov": true,
        "Dec": true
    },
    {
        "Name": "Black bass",
        "Image": "NH-Icon-blackbass",
        "Price": 400,
        "Location": "River",
        "Shadowsize": 4,
        "Time": "All day",
        "Jan": true,
        "Feb": true,
        "Mar": true,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": true,
        "Nov": true,
        "Dec": true
    },
    {
        "Name": "Tilapia",
        "Image": "NH-Icon-tilapia",
        "Price": 800,
        "Location": "River",
        "Shadowsize": 3,
        "Time": "All day",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": true,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Pike",
        "Image": "NH-Icon-pike",
        "Price": "1,800",
        "Location": "River",
        "Shadowsize": 5,
        "Time": "All day",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": false,
        "Jul": false,
        "Aug": false,
        "Sep": true,
        "Oct": true,
        "Nov": true,
        "Dec": true
    },
    {
        "Name": "Pond smelt",
        "Image": "NH-Icon-pondsmelt",
        "Price": 500,
        "Location": "River",
        "Shadowsize": 2,
        "Time": "All day",
        "Jan": true,
        "Feb": true,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": false,
        "Jul": false,
        "Aug": false,
        "Sep": false,
        "Oct": false,
        "Nov": false,
        "Dec": true
    },
    {
        "Name": "Sweetfish",
        "Image": "NH-Icon-sweetfish",
        "Price": 900,
        "Location": "River",
        "Shadowsize": 3,
        "Time": "All day",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": false,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Cherry salmon",
        "Image": "NH-Icon-cherrysalmon",
        "Price": "1,000",
        "Location": "River (Clifftop)",
        "Shadowsize": 3,
        "Time": "4 PM - 9 AM",
        "Jan": false,
        "Feb": false,
        "Mar": true,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": false,
        "Aug": false,
        "Sep": true,
        "Oct": true,
        "Nov": true,
        "Dec": false
    },
    {
        "Name": "Char",
        "Image": "NH-Icon-char",
        "Price": "3,800",
        "Location": "River (Clifftop) Pond",
        "Shadowsize": 3,
        "Time": "4 PM - 9 AM",
        "Jan": false,
        "Feb": false,
        "Mar": true,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": false,
        "Aug": false,
        "Sep": true,
        "Oct": true,
        "Nov": true,
        "Dec": false
    },
    {
        "Name": "Golden trout",
        "Image": "NH-Icon-goldentrout",
        "Price": "15,000",
        "Location": "River (Clifftop)",
        "Shadowsize": 3,
        "Time": "4 PM - 9 AM",
        "Jan": false,
        "Feb": false,
        "Mar": true,
        "Apr": true,
        "May": true,
        "Jun": false,
        "Jul": false,
        "Aug": false,
        "Sep": true,
        "Oct": true,
        "Nov": true,
        "Dec": false
    },
    {
        "Name": "Stringfish",
        "Image": "NH-Icon-stringfish",
        "Price": "15,000",
        "Location": "River (Clifftop)",
        "Shadowsize": 5,
        "Time": "4 PM - 9 AM",
        "Jan": true,
        "Feb": true,
        "Mar": true,
        "Apr": false,
        "May": false,
        "Jun": false,
        "Jul": false,
        "Aug": false,
        "Sep": false,
        "Oct": false,
        "Nov": false,
        "Dec": true
    },
    {
        "Name": "Salmon",
        "Image": "NH-Icon-salmon",
        "Price": 700,
        "Location": "River (Mouth)",
        "Shadowsize": 4,
        "Time": "All day",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": false,
        "Jul": false,
        "Aug": false,
        "Sep": true,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "King salmon",
        "Image": "NH-Icon-kingsalmon",
        "Price": "1,800",
        "Location": "River (Mouth)",
        "Shadowsize": 5,
        "Time": "All day",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": false,
        "Jul": false,
        "Aug": false,
        "Sep": true,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Mitten crab",
        "Image": "NH-Icon-mittencrab",
        "Price": "2,000",
        "Location": "River",
        "Shadowsize": 2,
        "Time": "4 PM - 9 AM",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": false,
        "Jul": false,
        "Aug": false,
        "Sep": true,
        "Oct": true,
        "Nov": true,
        "Dec": false
    },
    {
        "Name": "Guppy",
        "Image": "NH-Icon-guppy",
        "Price": "1,300",
        "Location": "River",
        "Shadowsize": 1,
        "Time": "9 AM - 4 PM",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": true,
        "Nov": true,
        "Dec": false
    },
    {
        "Name": "Nibble fish",
        "Image": "NH-Icon-nibblefish",
        "Price": "1,500",
        "Location": "River",
        "Shadowsize": 1,
        "Time": "9 AM - 4 PM",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Angelfish",
        "Image": "NH-Icon-angelfish",
        "Price": "3,000",
        "Location": "River",
        "Shadowsize": 2,
        "Time": "4 PM - 9 AM",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": true,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Betta",
        "Image": "NH-Icon-betta",
        "Price": "2,500",
        "Location": "River",
        "Shadowsize": 2,
        "Time": "9 AM - 4 PM",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": true,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Neon tetra",
        "Image": "NH-Icon-neontetra",
        "Price": 500,
        "Location": "River",
        "Shadowsize": 1,
        "Time": "9 AM - 4 PM",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": true,
        "Nov": true,
        "Dec": false
    },
    {
        "Name": "Rainbowfish",
        "Image": "NH-Icon-rainbowfish",
        "Price": 800,
        "Location": "River",
        "Shadowsize": 1,
        "Time": "9 AM - 4 PM",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": true,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Piranha",
        "Image": "NH-Icon-piranha",
        "Price": "2,500",
        "Location": "River",
        "Shadowsize": 2,
        "Time": "9 AM - 4 PM & 9 PM - 4 AM",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Arowana",
        "Image": "NH-Icon-arowana",
        "Price": "10,000",
        "Location": "River",
        "Shadowsize": 4,
        "Time": "4 PM - 9 AM",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Dorado",
        "Image": "NH-Icon-dorado",
        "Price": "15,000",
        "Location": "River",
        "Shadowsize": 5,
        "Time": "4 AM - 9 PM",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Gar",
        "Image": "NH-Icon-gar",
        "Price": "6,000",
        "Location": "Pond",
        "Shadowsize": 5,
        "Time": "4 PM - 9 AM",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Arapaima",
        "Image": "NH-Icon-arapaima",
        "Price": "10,000",
        "Location": "River",
        "Shadowsize": 6,
        "Time": "4 PM - 9 AM",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Saddled bichir",
        "Image": "NH-Icon-saddledbichir",
        "Price": "4,000",
        "Location": "River",
        "Shadowsize": 4,
        "Time": "9 PM - 4 AM",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Sturgeon",
        "Image": "NH-Icon-sturgeon",
        "Price": "10,000",
        "Location": "River (Mouth)",
        "Shadowsize": 6,
        "Time": "All day",
        "Jan": true,
        "Feb": true,
        "Mar": true,
        "Apr": false,
        "May": false,
        "Jun": false,
        "Jul": false,
        "Aug": false,
        "Sep": true,
        "Oct": true,
        "Nov": true,
        "Dec": true
    },
    {
        "Name": "Sea butterfly",
        "Image": "NH-Icon-seabutterfly",
        "Price": "1,000",
        "Location": "Sea",
        "Shadowsize": 1,
        "Time": "All day",
        "Jan": true,
        "Feb": true,
        "Mar": true,
        "Apr": false,
        "May": false,
        "Jun": false,
        "Jul": false,
        "Aug": false,
        "Sep": false,
        "Oct": false,
        "Nov": false,
        "Dec": true
    },
    {
        "Name": "Sea horse",
        "Image": "NH-Icon-seahorse",
        "Price": "1,100",
        "Location": "Sea",
        "Shadowsize": 1,
        "Time": "All day",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": true,
        "Nov": true,
        "Dec": false
    },
    {
        "Name": "Clown fish",
        "Image": "NH-Icon-clownfish",
        "Price": 650,
        "Location": "Sea",
        "Shadowsize": 1,
        "Time": "All day",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Surgeonfish",
        "Image": "NH-Icon-surgeonfish",
        "Price": "1,000",
        "Location": "Sea",
        "Shadowsize": 2,
        "Time": "All day",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Butterfly fish",
        "Image": "NH-Icon-butterflyfish",
        "Price": "1,000",
        "Location": "Sea",
        "Shadowsize": 2,
        "Time": "All day",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Napoleonfish",
        "Image": "NH-Icon-napoleonfish",
        "Price": "10,000",
        "Location": "Sea",
        "Shadowsize": 6,
        "Time": "4 AM - 9 PM",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": false,
        "Jul": true,
        "Aug": true,
        "Sep": false,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Zebra turkeyfish",
        "Image": "NH-Icon-zebraturkeyfish",
        "Price": 500,
        "Location": "Sea",
        "Shadowsize": 3,
        "Time": "All day",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": true,
        "Nov": true,
        "Dec": false
    },
    {
        "Name": "Blowfish",
        "Image": "NH-Icon-blowfish",
        "Price": "5,000",
        "Location": "Sea",
        "Shadowsize": 3,
        "Time": "9 PM - 4 AM",
        "Jan": true,
        "Feb": true,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": false,
        "Jul": false,
        "Aug": false,
        "Sep": false,
        "Oct": false,
        "Nov": true,
        "Dec": true
    },
    {
        "Name": "Puffer fish",
        "Image": "NH-Icon-pufferfish",
        "Price": 250,
        "Location": "Sea",
        "Shadowsize": 3,
        "Time": "All day",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": false,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Anchovy",
        "Image": "NH-Icon-anchovy",
        "Price": 200,
        "Location": "Sea",
        "Shadowsize": 2,
        "Time": "4 AM - 9 PM",
        "Jan": true,
        "Feb": true,
        "Mar": true,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": true,
        "Nov": true,
        "Dec": true
    },
    {
        "Name": "Horse mackerel",
        "Image": "NH-Icon-horsemackerel",
        "Price": 150,
        "Location": "Sea",
        "Shadowsize": 2,
        "Time": "All day",
        "Jan": true,
        "Feb": true,
        "Mar": true,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": true,
        "Nov": true,
        "Dec": true
    },
    {
        "Name": "Barred knifejaw",
        "Image": "NH-Icon-barredknifejaw",
        "Price": "5,000",
        "Location": "Sea",
        "Shadowsize": 3,
        "Time": "All day",
        "Jan": false,
        "Feb": false,
        "Mar": true,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": true,
        "Nov": true,
        "Dec": false
    },
    {
        "Name": "Sea bass",
        "Image": "NH-Icon-seabass",
        "Price": 400,
        "Location": "Sea",
        "Shadowsize": 5,
        "Time": "All day",
        "Jan": true,
        "Feb": true,
        "Mar": true,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": true,
        "Nov": true,
        "Dec": true
    },
    {
        "Name": "Red snapper",
        "Image": "NH-Icon-redsnapper",
        "Price": "3,000",
        "Location": "Sea",
        "Shadowsize": 4,
        "Time": "All day",
        "Jan": true,
        "Feb": true,
        "Mar": true,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": true,
        "Nov": true,
        "Dec": true
    },
    {
        "Name": "Dab",
        "Image": "NH-Icon-dab",
        "Price": 300,
        "Location": "Sea",
        "Shadowsize": 3,
        "Time": "All day",
        "Jan": true,
        "Feb": true,
        "Mar": true,
        "Apr": true,
        "May": false,
        "Jun": false,
        "Jul": false,
        "Aug": false,
        "Sep": false,
        "Oct": true,
        "Nov": true,
        "Dec": true
    },
    {
        "Name": "Olive flounder",
        "Image": "NH-Icon-oliveflounder",
        "Price": 800,
        "Location": "Sea",
        "Shadowsize": 5,
        "Time": "All day",
        "Jan": true,
        "Feb": true,
        "Mar": true,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": true,
        "Nov": true,
        "Dec": true
    },
    {
        "Name": "Squid",
        "Image": "NH-Icon-squid",
        "Price": 500,
        "Location": "Sea",
        "Shadowsize": 3,
        "Time": "All day",
        "Jan": true,
        "Feb": true,
        "Mar": true,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": false,
        "Oct": false,
        "Nov": false,
        "Dec": true
    },
    {
        "Name": "Moray eel",
        "Image": "NH-Icon-morayeel",
        "Price": "2,000",
        "Location": "Sea",
        "Shadowsize": "Narrow",
        "Time": "All day",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": false,
        "Jul": false,
        "Aug": true,
        "Sep": true,
        "Oct": true,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Ribbon eel",
        "Image": "NH-Icon-ribboneel",
        "Price": 600,
        "Location": "Sea",
        "Shadowsize": "Narrow",
        "Time": "All day",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": true,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Tuna",
        "Image": "NH-Icon-tuna",
        "Price": "7,000",
        "Location": "Pier",
        "Shadowsize": 6,
        "Time": "All day",
        "Jan": true,
        "Feb": true,
        "Mar": true,
        "Apr": true,
        "May": false,
        "Jun": false,
        "Jul": false,
        "Aug": false,
        "Sep": false,
        "Oct": false,
        "Nov": true,
        "Dec": true
    },
    {
        "Name": "Blue marlin",
        "Image": "NH-Icon-bluemarlin",
        "Price": "10,000",
        "Location": "Pier",
        "Shadowsize": 6,
        "Time": "All day",
        "Jan": true,
        "Feb": true,
        "Mar": true,
        "Apr": true,
        "May": false,
        "Jun": false,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": false,
        "Nov": true,
        "Dec": true
    },
    {
        "Name": "Giant trevally",
        "Image": "NH-Icon-gianttrevally",
        "Price": "4,500",
        "Location": "Pier",
        "Shadowsize": 5,
        "Time": "All day",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": true,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Mahi-mahi",
        "Image": "NH-Icon-mahimahi",
        "Price": "6,000",
        "Location": "Pier",
        "Shadowsize": 5,
        "Time": "All day",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": true,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Ocean sunfish",
        "Image": "NH-Icon-oceansunfish",
        "Price": "4,000",
        "Location": "Sea",
        "Shadowsize": "6 (Fin)",
        "Time": "4 AM - 9 PM",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": false,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Ray",
        "Image": "NH-Icon-ray",
        "Price": "3,000",
        "Location": "Sea",
        "Shadowsize": 5,
        "Time": "4 AM - 9 PM",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": false,
        "Jul": false,
        "Aug": true,
        "Sep": true,
        "Oct": true,
        "Nov": true,
        "Dec": false
    },
    {
        "Name": "Saw shark",
        "Image": "NH-Icon-sawshark",
        "Price": "12,000",
        "Location": "Sea",
        "Shadowsize": "6 (Fin)",
        "Time": "4 PM - 9 AM",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Hammerhead shark",
        "Image": "NH-Icon-hammerheadshark",
        "Price": "8,000",
        "Location": "Sea",
        "Shadowsize": "6 (Fin)",
        "Time": "4 PM - 9 AM",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Great white shark",
        "Image": "NH-Icon-greatwhiteshark",
        "Price": "15,000",
        "Location": "Sea",
        "Shadowsize": "6 (Fin)",
        "Time": "4 PM - 9 AM",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Whale shark",
        "Image": "NH-Icon-whaleshark",
        "Price": "13,000",
        "Location": "Sea",
        "Shadowsize": "6 (Fin)",
        "Time": "All day",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Suckerfish",
        "Image": "NH-Icon-suckerfish",
        "Price": "1,500",
        "Location": "Sea",
        "Shadowsize": "6 (Fin)",
        "Time": "All day",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Football fish",
        "Image": "NH-Icon-footballfish",
        "Price": "2,500",
        "Location": "Sea",
        "Shadowsize": 4,
        "Time": "4 PM - 9 AM",
        "Jan": true,
        "Feb": true,
        "Mar": true,
        "Apr": false,
        "May": false,
        "Jun": false,
        "Jul": false,
        "Aug": false,
        "Sep": false,
        "Oct": false,
        "Nov": true,
        "Dec": true
    },
    {
        "Name": "Oarfish",
        "Image": "NH-Icon-oarfish",
        "Price": "9,000",
        "Location": "Sea",
        "Shadowsize": 6,
        "Time": "All day",
        "Jan": true,
        "Feb": true,
        "Mar": true,
        "Apr": true,
        "May": true,
        "Jun": false,
        "Jul": false,
        "Aug": false,
        "Sep": false,
        "Oct": false,
        "Nov": false,
        "Dec": true
    },
    {
        "Name": "Barreleye",
        "Image": "NH-Icon-barreleye",
        "Price": "15,000",
        "Location": "Sea",
        "Shadowsize": 2,
        "Time": "9 PM - 4 AM",
        "Jan": true,
        "Feb": true,
        "Mar": true,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": true,
        "Nov": true,
        "Dec": true
    },
    {
        "Name": "Coelacanth",
        "Image": "NH-Icon-coelacanth",
        "Price": "15,000",
        "Location": "Sea",
        "Shadowsize": 6,
        "Time": "All day",
        "Jan": true,
        "Feb": true,
        "Mar": true,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": true,
        "Nov": true,
        "Dec": true
    }
]

var bugs_data = [
    {
        "Name": "Common butterfly",
        "Image": "NH-Icon-commonbutterfly",
        "Price": 160,
        "Location": "Flying",
        "Time": "4 AM - 7 PM",
        "Jan": true,
        "Feb": true,
        "Mar": true,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": false,
        "Aug": false,
        "Sep": true,
        "Oct": true,
        "Nov": true,
        "Dec": true
    },
    {
        "Name": "Yellow butterfly",
        "Image": "NH-Icon-yellowbutterfly",
        "Price": 160,
        "Location": "Flying",
        "Time": "4 AM - 7 PM",
        "Jan": false,
        "Feb": false,
        "Mar": true,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": false,
        "Aug": false,
        "Sep": true,
        "Oct": true,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Tiger butterfly",
        "Image": "NH-Icon-tigerbutterfly",
        "Price": 240,
        "Location": "Flying",
        "Time": "4 AM - 7 PM",
        "Jan": false,
        "Feb": false,
        "Mar": true,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Peacock butterfly",
        "Image": "NH-Icon-peacockbutterfly",
        "Price": "2,500",
        "Location": "Flying by Hybrid Flowers",
        "Time": "4 AM - 7 PM",
        "Jan": false,
        "Feb": false,
        "Mar": true,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": false,
        "Aug": false,
        "Sep": false,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Common bluebottle",
        "Image": "NH-Icon-commonbluebottle",
        "Price": 300,
        "Location": "Flying",
        "Time": "4 AM - 7 PM",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": false,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Paper kite butterfly",
        "Image": "NH-Icon-paperkitebutterfly",
        "Price": "1,000",
        "Location": "Flying",
        "Time": "8 AM - 7 PM",
        "Jan": true,
        "Feb": true,
        "Mar": true,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": true,
        "Nov": true,
        "Dec": true
    },
    {
        "Name": "Great purple emperor",
        "Image": "NH-Icon-greatpurpleemperor",
        "Price": "3,000",
        "Location": "Flying",
        "Time": "4 AM - 7 PM",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": false,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Monarch butterfly",
        "Image": "NH-Icon-monarchbutterfly",
        "Price": 140,
        "Location": "Flying",
        "Time": "4 AM - 5 PM",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": false,
        "Jul": false,
        "Aug": false,
        "Sep": true,
        "Oct": true,
        "Nov": true,
        "Dec": false
    },
    {
        "Name": "Emperor butterfly",
        "Image": "NH-Icon-emperorbutterfly",
        "Price": "4,000",
        "Location": "Flying",
        "Time": "5 PM - 8 AM",
        "Jan": true,
        "Feb": true,
        "Mar": true,
        "Apr": false,
        "May": false,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": false,
        "Nov": false,
        "Dec": true
    },
    {
        "Name": "Agrias butterfly",
        "Image": "NH-Icon-agriasbutterfly",
        "Price": "3,000",
        "Location": "Flying",
        "Time": "8 AM - 5 PM",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Rajah Brooke's birdwing",
        "Image": "NH-Icon-rajahbrookesbirdwing",
        "Price": "2,500",
        "Location": "Flying",
        "Time": "8 AM - 5 PM",
        "Jan": true,
        "Feb": true,
        "Mar": false,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": false,
        "Nov": false,
        "Dec": true
    },
    {
        "Name": "Queen Alexandra's birdwing",
        "Image": "NH-Icon-queenalexandrasbirdwing",
        "Price": "4,000",
        "Location": "Flying",
        "Time": "8 AM - 4 PM",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Moth",
        "Image": "NH-Icon-moth",
        "Price": 130,
        "Location": "Flying by Light",
        "Time": "7 PM - 4 AM",
        "Jan": true,
        "Feb": true,
        "Mar": true,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": true,
        "Nov": true,
        "Dec": true
    },
    {
        "Name": "Atlas moth",
        "Image": "NH-Icon-atlasmoth",
        "Price": "3,000",
        "Location": "On Trees",
        "Time": "7 PM - 4 AM",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Madagascan sunset moth",
        "Image": "NH-Icon-madagascansunsetmoth",
        "Price": "2,500",
        "Location": "Flying",
        "Time": "8 AM - 4 PM",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Long locust",
        "Image": "NH-Icon-longlocust",
        "Price": 200,
        "Location": "On the Ground",
        "Time": "8 AM - 7 PM",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": true,
        "Nov": true,
        "Dec": false
    },
    {
        "Name": "Migratory locust",
        "Image": "NH-Icon-migratorylocust",
        "Price": 600,
        "Location": "On the Ground",
        "Time": "8 AM - 7 PM",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": false,
        "Jul": false,
        "Aug": true,
        "Sep": true,
        "Oct": true,
        "Nov": true,
        "Dec": false
    },
    {
        "Name": "Rice grasshopper",
        "Image": "NH-Icon-ricegrasshopper",
        "Price": 160,
        "Location": "On the Ground",
        "Time": "8 AM - 7 PM",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": false,
        "Jul": false,
        "Aug": true,
        "Sep": true,
        "Oct": true,
        "Nov": true,
        "Dec": false
    },
    {
        "Name": "Grasshopper",
        "Image": "NH-Icon-grasshopper",
        "Price": 160,
        "Location": "On the Ground",
        "Time": "8 AM - 5 PM",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": false,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Cricket",
        "Image": "NH-Icon-cricket",
        "Price": 130,
        "Location": "On the Ground",
        "Time": "5 PM - 8 AM",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": false,
        "Jul": false,
        "Aug": false,
        "Sep": true,
        "Oct": true,
        "Nov": true,
        "Dec": false
    },
    {
        "Name": "Bell cricket",
        "Image": "NH-Icon-bellcricket",
        "Price": 430,
        "Location": "On the Ground",
        "Time": "5 PM - 8 AM",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": false,
        "Jul": false,
        "Aug": false,
        "Sep": true,
        "Oct": true,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Mantis",
        "Image": "NH-Icon-mantis",
        "Price": 430,
        "Location": "On Flowers",
        "Time": "8 AM - 5 PM",
        "Jan": false,
        "Feb": false,
        "Mar": true,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": true,
        "Nov": true,
        "Dec": false
    },
    {
        "Name": "Orchid mantis",
        "Image": "NH-Icon-orchidmantis",
        "Price": "2,400",
        "Location": "On Flowers (White)",
        "Time": "8 AM - 5 PM",
        "Jan": false,
        "Feb": false,
        "Mar": true,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": true,
        "Nov": true,
        "Dec": false
    },
    {
        "Name": "Honeybee",
        "Image": "NH-Icon-honeybee",
        "Price": 200,
        "Location": "Flying",
        "Time": "8 AM - 5 PM",
        "Jan": false,
        "Feb": false,
        "Mar": true,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": false,
        "Sep": false,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Wasp",
        "Image": "NH-Icon-wasp",
        "Price": "2,500",
        "Location": "Shaking Trees",
        "Time": "All day",
        "Jan": true,
        "Feb": true,
        "Mar": true,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": true,
        "Nov": true,
        "Dec": true
    },
    {
        "Name": "Brown cicada",
        "Image": "NH-Icon-browncicada",
        "Price": 250,
        "Location": "On Trees",
        "Time": "8 AM - 5 PM",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": false,
        "Jul": true,
        "Aug": true,
        "Sep": false,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Robust cicada",
        "Image": "NH-Icon-robustcicada",
        "Price": 300,
        "Location": "On Trees",
        "Time": "8 AM - 5 PM",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": false,
        "Jul": true,
        "Aug": true,
        "Sep": false,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Giant cicada",
        "Image": "NH-Icon-giantcicada",
        "Price": 500,
        "Location": "On Trees",
        "Time": "8 AM - 5 PM",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": false,
        "Jul": true,
        "Aug": true,
        "Sep": false,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Walker cicada",
        "Image": "NH-Icon-walkercicada",
        "Price": 400,
        "Location": "On Trees",
        "Time": "8 AM - 5 PM",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": false,
        "Jul": false,
        "Aug": true,
        "Sep": true,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Evening cicada",
        "Image": "NH-Icon-eveningcicada",
        "Price": 550,
        "Location": "On Trees",
        "Time": "4 AM - 8 AM & 4 PM - 7 PM",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": false,
        "Jul": true,
        "Aug": true,
        "Sep": false,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Cicada shell",
        "Image": "NH-Icon-cicadashell",
        "Price": 10,
        "Location": "On Trees",
        "Time": "All day",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": false,
        "Jul": true,
        "Aug": true,
        "Sep": false,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Red dragonfly",
        "Image": "NH-Icon-reddragonfly",
        "Price": 180,
        "Location": "Flying",
        "Time": "8 AM - 7 PM",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": false,
        "Jul": false,
        "Aug": false,
        "Sep": true,
        "Oct": true,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Darner dragonfly",
        "Image": "NH-Icon-darnerdragonfly",
        "Price": 230,
        "Location": "Flying",
        "Time": "8 AM - 5 PM",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": true,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Banded dragonfly",
        "Image": "NH-Icon-bandeddragonfly",
        "Price": "4,500",
        "Location": "Flying",
        "Time": "8 AM - 5 PM",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": true,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Damselfly",
        "Image": "NH-Icon-damselfly",
        "Price": 500,
        "Location": "Flying",
        "Time": "All day",
        "Jan": true,
        "Feb": true,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": false,
        "Jul": false,
        "Aug": false,
        "Sep": false,
        "Oct": false,
        "Nov": true,
        "Dec": true
    },
    {
        "Name": "Firefly",
        "Image": "NH-Icon-firefly",
        "Price": 300,
        "Location": "Flying",
        "Time": "7 PM - 4 AM",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": true,
        "Jul": false,
        "Aug": false,
        "Sep": false,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Mole cricket",
        "Image": "NH-Icon-molecricket",
        "Price": 500,
        "Location": "Underground",
        "Time": "All day",
        "Jan": true,
        "Feb": true,
        "Mar": true,
        "Apr": true,
        "May": true,
        "Jun": false,
        "Jul": false,
        "Aug": false,
        "Sep": false,
        "Oct": false,
        "Nov": true,
        "Dec": true
    },
    {
        "Name": "Pondskater",
        "Image": "NH-Icon-pondskater",
        "Price": 130,
        "Location": "On Ponds and Rivers",
        "Time": "8 AM - 7 PM",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Diving beetle",
        "Image": "NH-Icon-divingbeetle",
        "Price": 800,
        "Location": "On Ponds and Rivers",
        "Time": "8 AM - 7 PM",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Giant water bug",
        "Image": "NH-Icon-giantwaterbug",
        "Price": "2,000",
        "Location": "On Ponds and Rivers",
        "Time": "7 PM - 8 AM",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Stinkbug",
        "Image": "NH-Icon-stinkbug",
        "Price": 120,
        "Location": "On Flowers",
        "Time": "All day",
        "Jan": false,
        "Feb": false,
        "Mar": true,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": true,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Man-faced stink bug",
        "Image": "NH-Icon-manfacedstinkbug",
        "Price": "1,000",
        "Location": "On Flowers",
        "Time": "7 PM - 8 AM",
        "Jan": false,
        "Feb": false,
        "Mar": true,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": true,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Ladybug",
        "Image": "NH-Icon-ladybug",
        "Price": 200,
        "Location": "On Flowers",
        "Time": "8 AM - 5 PM",
        "Jan": false,
        "Feb": false,
        "Mar": true,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": false,
        "Aug": false,
        "Sep": false,
        "Oct": true,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Tiger beetle",
        "Image": "NH-Icon-tigerbeetle",
        "Price": "1,500",
        "Location": "On the Ground",
        "Time": "All day",
        "Jan": false,
        "Feb": true,
        "Mar": true,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": true,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Jewel beetle",
        "Image": "NH-Icon-jewelbeetle",
        "Price": "2,400",
        "Location": "On Tree Stumps",
        "Time": "All day",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": false,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Violin beetle",
        "Image": "NH-Icon-violinbeetle",
        "Price": 450,
        "Location": "On Tree Stumps",
        "Time": "All day",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": true,
        "Jun": true,
        "Jul": false,
        "Aug": false,
        "Sep": true,
        "Oct": true,
        "Nov": true,
        "Dec": false
    },
    {
        "Name": "Citrus long-horned beetle",
        "Image": "NH-Icon-citruslonghornedbeetle",
        "Price": 350,
        "Location": "On Tree Stumps",
        "Time": "All day",
        "Jan": true,
        "Feb": true,
        "Mar": true,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": true,
        "Nov": true,
        "Dec": true
    },
    {
        "Name": "Rosalia batesi beetle",
        "Image": "NH-Icon-rosaliabatesibeetle",
        "Price": "3,000",
        "Location": "On Tree Stumps",
        "Time": "All day",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Blue weevil beetle",
        "Image": "NH-Icon-blueweevilbeetle",
        "Price": 800,
        "Location": "On Trees (Coconut)",
        "Time": "All day",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": false,
        "Jul": true,
        "Aug": true,
        "Sep": false,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Dung beetle",
        "Image": "NH-Icon-dungbeetle",
        "Price": "3,000",
        "Location": "On the Ground (rolling snowballs)",
        "Time": "All day",
        "Jan": true,
        "Feb": true,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": false,
        "Jul": false,
        "Aug": false,
        "Sep": false,
        "Oct": false,
        "Nov": false,
        "Dec": true
    },
    {
        "Name": "Earth-boring dung beetle",
        "Image": "NH-Icon-earthboringdungbeetle",
        "Price": 300,
        "Location": "On the Ground",
        "Time": "All day",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": false,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Scarab beetle",
        "Image": "NH-Icon-scarabbeetle",
        "Price": "10,000",
        "Location": "On Trees",
        "Time": "11 PM - 8 AM",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": false,
        "Jul": true,
        "Aug": true,
        "Sep": false,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Drone beetle",
        "Image": "NH-Icon-dronebeetle",
        "Price": 200,
        "Location": "On Trees",
        "Time": "All day",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": false,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Goliath beetle",
        "Image": "NH-Icon-goliathbeetle",
        "Price": "8,000",
        "Location": "On Trees (Coconut)",
        "Time": "5 PM - 8 AM",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Saw stag",
        "Image": "NH-Icon-sawstag",
        "Price": "2,000",
        "Location": "On Trees",
        "Time": "All day",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": false,
        "Jul": true,
        "Aug": true,
        "Sep": false,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Miyama stag",
        "Image": "NH-Icon-miyamastag",
        "Price": "1,000",
        "Location": "On Trees",
        "Time": "All day",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": false,
        "Jul": true,
        "Aug": true,
        "Sep": false,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Giant stag",
        "Image": "NH-Icon-giantstag",
        "Price": "10,000",
        "Location": "On Trees",
        "Time": "11 PM - 8 AM",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": false,
        "Jul": true,
        "Aug": true,
        "Sep": false,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Rainbow stag",
        "Image": "NH-Icon-rainbowstag",
        "Price": "6,000",
        "Location": "On Trees",
        "Time": "7 PM - 8 AM",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Cyclommatus stag",
        "Image": "NH-Icon-cyclommatusstag",
        "Price": "8,000",
        "Location": "On Trees (Coconut)",
        "Time": "5 PM - 8 AM",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": false,
        "Jul": true,
        "Aug": true,
        "Sep": false,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Golden stag",
        "Image": "NH-Icon-goldenstag",
        "Price": "12,000",
        "Location": "On Trees (Coconut)",
        "Time": "5 PM - 8 AM",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": false,
        "Jul": true,
        "Aug": true,
        "Sep": false,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Giraffe stag",
        "Image": "NH-Icon-giraffestag",
        "Price": "12,000",
        "Location": "On Trees (Coconut)",
        "Time": "5 PM - 8 AM",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": false,
        "Jul": true,
        "Aug": true,
        "Sep": false,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Horned dynastid",
        "Image": "NH-Icon-horneddynastid",
        "Price": "1,350",
        "Location": "On Trees",
        "Time": "5 PM - 8 AM",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": false,
        "Jul": true,
        "Aug": true,
        "Sep": false,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Horned atlas",
        "Image": "NH-Icon-hornedatlas",
        "Price": "8,000",
        "Location": "On Trees (Coconut)",
        "Time": "5 PM - 8 AM",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": false,
        "Jul": true,
        "Aug": true,
        "Sep": false,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Horned elephant",
        "Image": "NH-Icon-hornedelephant",
        "Price": "8,000",
        "Location": "On Trees (Coconut)",
        "Time": "5 PM - 8 AM",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": false,
        "Jul": true,
        "Aug": true,
        "Sep": false,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Horned hercules",
        "Image": "NH-Icon-hornedhercules",
        "Price": "12,000",
        "Location": "On Trees (Coconut)",
        "Time": "5 PM - 8 AM",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": false,
        "Jul": true,
        "Aug": true,
        "Sep": false,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Walking stick",
        "Image": "NH-Icon-walkingstick",
        "Price": 600,
        "Location": "On Trees",
        "Time": "4 AM - 8 AM & 5 PM - 7 PM",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": false,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": true,
        "Nov": true,
        "Dec": false
    },
    {
        "Name": "Walking leaf",
        "Image": "NH-Icon-walkingleaf",
        "Price": 600,
        "Location": "Under Trees Disguised as Leaves",
        "Time": "All day",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": false,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Bagworm",
        "Image": "NH-Icon-bagworm",
        "Price": 600,
        "Location": "Shaking Trees",
        "Time": "All day",
        "Jan": true,
        "Feb": true,
        "Mar": true,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": true,
        "Nov": true,
        "Dec": true
    },
    {
        "Name": "Ant",
        "Image": "NH-Icon-ant",
        "Price": 80,
        "Location": "On rotten food",
        "Time": "All day",
        "Jan": true,
        "Feb": true,
        "Mar": true,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": true,
        "Nov": true,
        "Dec": true
    },
    {
        "Name": "Hermit crab",
        "Image": "NH-Icon-hermitcrab",
        "Price": "1,000",
        "Location": "Beach disguised as Shells",
        "Time": "7 PM - 8 AM",
        "Jan": true,
        "Feb": true,
        "Mar": true,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": true,
        "Nov": true,
        "Dec": true
    },
    {
        "Name": "Wharf roach",
        "Image": "NH-Icon-wharfroach",
        "Price": 200,
        "Location": "On Beach Rocks",
        "Time": "All day",
        "Jan": true,
        "Feb": true,
        "Mar": true,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": true,
        "Nov": true,
        "Dec": true
    },
    {
        "Name": "Fly",
        "Image": "NH-Icon-fly",
        "Price": 60,
        "Location": "On Trash Items",
        "Time": "All day",
        "Jan": true,
        "Feb": true,
        "Mar": true,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": true,
        "Nov": true,
        "Dec": true
    },
    {
        "Name": "Mosquito",
        "Image": "NH-Icon-mosquito",
        "Price": 130,
        "Location": "Flying",
        "Time": "5 PM - 4 AM",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Flea",
        "Image": "NH-Icon-flea",
        "Price": 70,
        "Location": "Villager's Heads",
        "Time": "All day",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": true,
        "Nov": true,
        "Dec": false
    },
    {
        "Name": "Snail",
        "Image": "NH-Icon-snail",
        "Price": 250,
        "Location": "On Rocks and Bushes (Rain)",
        "Time": "All day",
        "Jan": true,
        "Feb": true,
        "Mar": true,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": true,
        "Nov": true,
        "Dec": true
    },
    {
        "Name": "Pill bug",
        "Image": "NH-Icon-pillbug",
        "Price": 250,
        "Location": "Hitting Rocks",
        "Time": "11 PM - 4 PM",
        "Jan": true,
        "Feb": true,
        "Mar": true,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": false,
        "Aug": false,
        "Sep": true,
        "Oct": true,
        "Nov": true,
        "Dec": true
    },
    {
        "Name": "Centipede",
        "Image": "NH-Icon-centipede",
        "Price": 300,
        "Location": "Hitting Rocks",
        "Time": "4 PM - 11 PM",
        "Jan": true,
        "Feb": true,
        "Mar": true,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": false,
        "Aug": false,
        "Sep": true,
        "Oct": true,
        "Nov": true,
        "Dec": true
    },
    {
        "Name": "Spider",
        "Image": "NH-Icon-spider",
        "Price": 600,
        "Location": "Shaking Trees",
        "Time": "7 PM - 8 AM",
        "Jan": true,
        "Feb": true,
        "Mar": true,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": true,
        "Nov": true,
        "Dec": true
    },
    {
        "Name": "Tarantula",
        "Image": "NH-Icon-tarantula",
        "Price": "8,000",
        "Location": "On the Ground",
        "Time": "7 PM - 4 AM",
        "Jan": true,
        "Feb": true,
        "Mar": true,
        "Apr": true,
        "May": false,
        "Jun": false,
        "Jul": false,
        "Aug": false,
        "Sep": false,
        "Oct": false,
        "Nov": true,
        "Dec": true
    },
    {
        "Name": "Scorpion",
        "Image": "NH-Icon-scorpion",
        "Price": "8,000",
        "Location": "On the Ground",
        "Time": "7 PM - 4 AM",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": true,
        "Nov": false,
        "Dec": false
    }
]

var sea_data = [
    {
        "Name": "Seaweed",
        "Image": "NH-Icon-seaweed",
        "Price": 600,
        "Shadowsize": "Large",
        "Swimming pattern": "Stationary",
        "Time": "All day",
        "Jan": true,
        "Feb": true,
        "Mar": true,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": false,
        "Sep": false,
        "Oct": true,
        "Nov": true,
        "Dec": true
    },
    {
        "Name": "Sea grapes",
        "Image": "NH-Icon-seagrapes",
        "Price": 900,
        "Shadowsize": "Small",
        "Swimming pattern": "Stationary",
        "Time": "All day",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Sea cucumber",
        "Image": "NH-Icon-seacucumber",
        "Price": 500,
        "Shadowsize": "Medium",
        "Swimming pattern": "Slow consistent movement",
        "Time": "All day",
        "Jan": true,
        "Feb": true,
        "Mar": true,
        "Apr": true,
        "May": false,
        "Jun": false,
        "Jul": false,
        "Aug": false,
        "Sep": false,
        "Oct": false,
        "Nov": true,
        "Dec": true
    },
    {
        "Name": "Sea pig",
        "Image": "NH-Icon-seapig",
        "Price": "10,000",
        "Shadowsize": "Small",
        "Swimming pattern": "Quick long lunges",
        "Time": "4pm - 9am",
        "Jan": true,
        "Feb": true,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": false,
        "Jul": false,
        "Aug": false,
        "Sep": false,
        "Oct": false,
        "Nov": true,
        "Dec": true
    },
    {
        "Name": "Sea star",
        "Image": "NH-Icon-seastar",
        "Price": 500,
        "Shadowsize": "Small",
        "Swimming pattern": "Slow short lunges",
        "Time": "All day",
        "Jan": true,
        "Feb": true,
        "Mar": true,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": true,
        "Nov": true,
        "Dec": true
    },
    {
        "Name": "Sea urchin",
        "Image": "NH-Icon-seaurchin",
        "Price": "1,700",
        "Shadowsize": "Small",
        "Swimming pattern": "Slow consistent movement",
        "Time": "All day",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Slate pencil urchin",
        "Image": "NH-Icon-slatepencilurchin",
        "Price": "2,000",
        "Shadowsize": "Medium",
        "Swimming pattern": "Moderate consistent movement",
        "Time": "4pm - 9am",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Sea anemone",
        "Image": "NH-Icon-seaanemone",
        "Price": 500,
        "Shadowsize": "Large",
        "Swimming pattern": "Stationary",
        "Time": "All day",
        "Jan": true,
        "Feb": true,
        "Mar": true,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": true,
        "Nov": true,
        "Dec": true
    },
    {
        "Name": "Moon jellyfish",
        "Image": "NH-Icon-moonjellyfish",
        "Price": 600,
        "Shadowsize": "Small",
        "Swimming pattern": "Slow consistent movement",
        "Time": "All day",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": false,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Sea slug",
        "Image": "NH-Icon-seaslug",
        "Price": 600,
        "Shadowsize": "Tiny",
        "Swimming pattern": "Slow consistent movement",
        "Time": "All day",
        "Jan": true,
        "Feb": true,
        "Mar": true,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": true,
        "Nov": true,
        "Dec": true
    },
    {
        "Name": "Pearl oyster",
        "Image": "NH-Icon-pearloyster",
        "Price": "2,800",
        "Shadowsize": "Small",
        "Swimming pattern": "Moderate long lunges",
        "Time": "All day",
        "Jan": true,
        "Feb": true,
        "Mar": true,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": true,
        "Nov": true,
        "Dec": true
    },
    {
        "Name": "Mussel",
        "Image": "NH-Icon-mussel",
        "Price": "1,500",
        "Shadowsize": "Small",
        "Swimming pattern": "Slow consistent movement",
        "Time": "All day",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": true,
        "Nov": true,
        "Dec": true
    },
    {
        "Name": "Oyster",
        "Image": "NH-Icon-oyster",
        "Price": "1,100",
        "Shadowsize": "Small",
        "Swimming pattern": "Moderate short lunges",
        "Time": "All day",
        "Jan": true,
        "Feb": true,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": false,
        "Jul": false,
        "Aug": false,
        "Sep": true,
        "Oct": true,
        "Nov": true,
        "Dec": true
    },
    {
        "Name": "Scallop",
        "Image": "NH-Icon-scallop",
        "Price": "1,200",
        "Shadowsize": "Medium",
        "Swimming pattern": "Slow long lunges",
        "Time": "All day",
        "Jan": true,
        "Feb": true,
        "Mar": true,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": true,
        "Nov": true,
        "Dec": true
    },
    {
        "Name": "Whelk",
        "Image": "NH-Icon-whelk",
        "Price": "1,000",
        "Shadowsize": "Small",
        "Swimming pattern": "Slow consistent movement",
        "Time": "All day",
        "Jan": true,
        "Feb": true,
        "Mar": true,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": true,
        "Nov": true,
        "Dec": true
    },
    {
        "Name": "Turban shell",
        "Image": "NH-Icon-turbanshell",
        "Price": "1,000",
        "Shadowsize": "Small",
        "Swimming pattern": "Slow",
        "Time": "All day",
        "Jan": false,
        "Feb": false,
        "Mar": true,
        "Apr": true,
        "May": true,
        "Jun": false,
        "Jul": false,
        "Aug": false,
        "Sep": true,
        "Oct": true,
        "Nov": true,
        "Dec": true
    },
    {
        "Name": "Abalone",
        "Image": "NH-Icon-abalone",
        "Price": "2,000",
        "Shadowsize": "Medium",
        "Swimming pattern": "Moderate consistent movement",
        "Time": "4pm - 9am",
        "Jan": true,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": true,
        "Nov": true,
        "Dec": true
    },
    {
        "Name": "Gigas giant clam",
        "Image": "NH-Icon-gigasgiantclam",
        "Price": "15,000",
        "Shadowsize": "Huge",
        "Swimming pattern": "Quick long lunges",
        "Time": "All day",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Chambered nautilus",
        "Image": "NH-Icon-chamberednautilus",
        "Price": "1,800",
        "Shadowsize": "Medium",
        "Swimming pattern": "Slow",
        "Time": "4pm - 9am",
        "Jan": false,
        "Feb": false,
        "Mar": true,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": false,
        "Aug": false,
        "Sep": true,
        "Oct": true,
        "Nov": true,
        "Dec": false
    },
    {
        "Name": "Octopus",
        "Image": "NH-Icon-octopus",
        "Price": "1,200",
        "Shadowsize": "Medium",
        "Swimming pattern": "Moderate long lunges",
        "Time": "All day",
        "Jan": true,
        "Feb": true,
        "Mar": true,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": true,
        "Nov": true,
        "Dec": true
    },
    {
        "Name": "Umbrella octopus",
        "Image": "NH-Icon-umbrellaoctopus",
        "Price": "6,000",
        "Shadowsize": "Small",
        "Swimming pattern": "Quick long lunges",
        "Time": "All day",
        "Jan": false,
        "Feb": false,
        "Mar": true,
        "Apr": true,
        "May": true,
        "Jun": false,
        "Jul": false,
        "Aug": false,
        "Sep": true,
        "Oct": true,
        "Nov": true,
        "Dec": false
    },
    {
        "Name": "Vampire squid",
        "Image": "NH-Icon-vampiresquid",
        "Price": "10,000",
        "Shadowsize": "Medium",
        "Swimming pattern": "Quick long lunges",
        "Time": "4pm - 9am",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": false,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Firefly squid",
        "Image": "NH-Icon-fireflysquid",
        "Price": "1,400",
        "Shadowsize": "Tiny",
        "Swimming pattern": "Slow",
        "Time": "9pm - 4am",
        "Jan": false,
        "Feb": false,
        "Mar": true,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": false,
        "Aug": false,
        "Sep": false,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Gazami crab",
        "Image": "NH-Icon-gazamicrab",
        "Price": "2,200",
        "Shadowsize": "Medium",
        "Swimming pattern": "Moderate long lunges",
        "Time": "All day",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": true,
        "Nov": true,
        "Dec": false
    },
    {
        "Name": "Dungeness crab",
        "Image": "NH-Icon-dungenesscrab",
        "Price": "1,900",
        "Shadowsize": "Medium",
        "Swimming pattern": "Moderate consistent movement",
        "Time": "All day",
        "Jan": true,
        "Feb": true,
        "Mar": true,
        "Apr": true,
        "May": true,
        "Jun": false,
        "Jul": false,
        "Aug": false,
        "Sep": false,
        "Oct": false,
        "Nov": true,
        "Dec": true
    },
    {
        "Name": "Snow crab",
        "Image": "NH-Icon-snowcrab",
        "Price": "6,000",
        "Shadowsize": "Large",
        "Swimming pattern": "Quick short lunges",
        "Time": "All day",
        "Jan": true,
        "Feb": true,
        "Mar": true,
        "Apr": true,
        "May": false,
        "Jun": false,
        "Jul": false,
        "Aug": false,
        "Sep": false,
        "Oct": false,
        "Nov": true,
        "Dec": true
    },
    {
        "Name": "Red king crab",
        "Image": "NH-Icon-redkingcrab",
        "Price": "8,000",
        "Shadowsize": "Large",
        "Swimming pattern": "Quick",
        "Time": "All day",
        "Jan": true,
        "Feb": true,
        "Mar": true,
        "Apr": false,
        "May": false,
        "Jun": false,
        "Jul": false,
        "Aug": false,
        "Sep": false,
        "Oct": false,
        "Nov": true,
        "Dec": true
    },
    {
        "Name": "Acorn barnacle",
        "Image": "NH-Icon-acornbarnacle",
        "Price": 600,
        "Shadowsize": "Tiny",
        "Swimming pattern": "Stationary",
        "Time": "All day",
        "Jan": true,
        "Feb": true,
        "Mar": true,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": true,
        "Nov": true,
        "Dec": true
    },
    {
        "Name": "Spider crab",
        "Image": "NH-Icon-spidercrab",
        "Price": "12,000",
        "Shadowsize": "Huge",
        "Swimming pattern": "Quick",
        "Time": "All day",
        "Jan": false,
        "Feb": false,
        "Mar": true,
        "Apr": true,
        "May": false,
        "Jun": false,
        "Jul": false,
        "Aug": false,
        "Sep": false,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Tiger prawn",
        "Image": "NH-Icon-tigerprawn",
        "Price": "3,000",
        "Shadowsize": "Small",
        "Swimming pattern": "Moderate consistent movement",
        "Time": "4pm - 9am",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Sweet shrimp",
        "Image": "NH-Icon-sweetshrimp",
        "Price": "1,400",
        "Shadowsize": "Small",
        "Swimming pattern": "Slow",
        "Time": "4pm - 9am",
        "Jan": true,
        "Feb": true,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": false,
        "Jul": false,
        "Aug": false,
        "Sep": true,
        "Oct": true,
        "Nov": true,
        "Dec": true
    },
    {
        "Name": "Mantis shrimp",
        "Image": "NH-Icon-mantisshrimp",
        "Price": "2,500",
        "Shadowsize": "Small",
        "Swimming pattern": "Quick short lunges",
        "Time": "4pm - 9am",
        "Jan": true,
        "Feb": true,
        "Mar": true,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": true,
        "Nov": true,
        "Dec": true
    },
    {
        "Name": "Spiny lobster",
        "Image": "NH-Icon-spinylobster",
        "Price": "5,000",
        "Shadowsize": "Large",
        "Swimming pattern": "Fast",
        "Time": "9pm - 4am",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": false,
        "Jul": false,
        "Aug": false,
        "Sep": false,
        "Oct": true,
        "Nov": true,
        "Dec": true
    },
    {
        "Name": "Lobster",
        "Image": "NH-Icon-lobster",
        "Price": "4,500",
        "Shadowsize": "Large",
        "Swimming pattern": "Quick",
        "Time": "All day",
        "Jan": true,
        "Feb": false,
        "Mar": false,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": false,
        "Aug": false,
        "Sep": false,
        "Oct": false,
        "Nov": false,
        "Dec": true
    },
    {
        "Name": "Giant isopod",
        "Image": "NH-Icon-giantisopod",
        "Price": "12,000",
        "Shadowsize": "Medium",
        "Swimming pattern": "Quick long lunges",
        "Time": "9am - 4pm & 9pm - 4am",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": false,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": true,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Horseshoe Crab",
        "Image": "NH-Icon-horseshoecrab",
        "Price": "2,500",
        "Shadowsize": "Medium",
        "Swimming pattern": "Quick short lunges",
        "Time": "9pm - 4am",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": false,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Sea pineapple",
        "Image": "NH-Icon-seapineapple",
        "Price": "1,500",
        "Shadowsize": "Small",
        "Swimming pattern": "Slow long lunges",
        "Time": "All day",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": true,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": false,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Spotted garden eel",
        "Image": "NH-Icon-spottedgardeneel",
        "Price": "1,100",
        "Shadowsize": "Small",
        "Swimming pattern": "Slow consistent movement",
        "Time": "4am - 9pm",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": true,
        "Jun": true,
        "Jul": true,
        "Aug": true,
        "Sep": true,
        "Oct": true,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Flatworm",
        "Image": "NH-Icon-flatworm",
        "Price": 700,
        "Shadowsize": "Tiny",
        "Swimming pattern": "Slow short movement",
        "Time": "4pm - 9am",
        "Jan": false,
        "Feb": false,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": false,
        "Jul": false,
        "Aug": true,
        "Sep": true,
        "Oct": false,
        "Nov": false,
        "Dec": false
    },
    {
        "Name": "Venus' flower basket",
        "Image": "NH-Icon-venusflowerbasket",
        "Price": "5,000",
        "Shadowsize": "Medium",
        "Swimming pattern": "Quick long lunges",
        "Time": "All day",
        "Jan": true,
        "Feb": true,
        "Mar": false,
        "Apr": false,
        "May": false,
        "Jun": false,
        "Jul": false,
        "Aug": false,
        "Sep": false,
        "Oct": true,
        "Nov": true,
        "Dec": true
    }
]